runtime: nodejs10
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
handlers:
  - url: /favicon.ico
    static_files: favicon.ico
    upload: /static/favicon.ico
  - url: /static
    static_dir: public
