runtime: nodejs10
automatic_scaling:
  min_idle_instances: automatic # idle状態にあるインスタンスの最小値
  max_idle_instances: 1 # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic

handlers:
  # - url: /favicon\.ico
  #   static_files: favicon.ico
  - url: /static
    static_dir: public
